import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "module";
import sveltePlugin from "esbuild-svelte";
import { access, copyFile } from "fs/promises";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

async function syncPluginStyles() {
    try {
        await access("main.css");
        await copyFile("main.css", "styles.css");
        console.log("Synced main.css -> styles.css");
    } catch (error) {
        console.warn("Skipping CSS sync:", error);
    }
}

const context = await esbuild.context({
    banner: {
        js: banner,
    },
    entryPoints: ["src/main.ts"],
    bundle: true,
    external: [
        "obsidian",
        "electron",
        "@codemirror/autocomplete",
        "@codemirror/collab",
        "@codemirror/commands",
        "@codemirror/language",
        "@codemirror/lint",
        "@codemirror/search",
        "@codemirror/state",
        "@codemirror/view",
        "@lezer/common",
        "@lezer/highlight",
        "@lezer/lr",
        ...builtinModules,
    ],
    format: "cjs",
    target: "es2018",
    logLevel: "info",
    plugins: [sveltePlugin()],
    outfile: "main.js",
    sourcemap: prod ? false : "inline",
    minify: prod,
});

if (prod) {
    await context.rebuild();
    await syncPluginStyles();
    process.exit(0);
} else {
    await context.watch();
}